package org.example.model

import org.hexworks.mixite.core.api.CubeCoordinate


val bitmaskNodes = mapOf<ULong, Node>(
	1UL to Node(coordinate=Coordinate(column='B', row=2), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='B', row=3), below=null, upperRight=Coordinate(column='C', row=3), lowerRight=Coordinate(column='C', row=2), upperLeft=null, lowerLeft=null), bitmask=1UL),
	2UL to Node(coordinate=Coordinate(column='B', row=3), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='B', row=4), below=Coordinate(column='B', row=2), upperRight=Coordinate(column='C', row=4), lowerRight=Coordinate(column='C', row=3), upperLeft=null, lowerLeft=null), bitmask=2UL),
	4UL to Node(coordinate=Coordinate(column='B', row=4), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='B', row=5), below=Coordinate(column='B', row=3), upperRight=Coordinate(column='C', row=5), lowerRight=Coordinate(column='C', row=4), upperLeft=null, lowerLeft=null), bitmask=4UL),
	8UL to Node(coordinate=Coordinate(column='B', row=5), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=null, below=Coordinate(column='B', row=4), upperRight=Coordinate(column='C', row=6), lowerRight=Coordinate(column='C', row=5), upperLeft=null, lowerLeft=null), bitmask=8UL),
	16UL to Node(coordinate=Coordinate(column='C', row=2), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='C', row=3), below=null, upperRight=Coordinate(column='D', row=3), lowerRight=Coordinate(column='D', row=2), upperLeft=Coordinate(column='B', row=2), lowerLeft=null), bitmask=16UL),
	32UL to Node(coordinate=Coordinate(column='C', row=3), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='C', row=4), below=Coordinate(column='C', row=2), upperRight=Coordinate(column='D', row=4), lowerRight=Coordinate(column='D', row=3), upperLeft=Coordinate(column='B', row=3), lowerLeft=Coordinate(column='B', row=2)), bitmask=32UL),
	64UL to Node(coordinate=Coordinate(column='C', row=4), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='C', row=5), below=Coordinate(column='C', row=3), upperRight=Coordinate(column='D', row=5), lowerRight=Coordinate(column='D', row=4), upperLeft=Coordinate(column='B', row=4), lowerLeft=Coordinate(column='B', row=3)), bitmask=64UL),
	128UL to Node(coordinate=Coordinate(column='C', row=5), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='C', row=6), below=Coordinate(column='C', row=4), upperRight=Coordinate(column='D', row=6), lowerRight=Coordinate(column='D', row=5), upperLeft=Coordinate(column='B', row=5), lowerLeft=Coordinate(column='B', row=4)), bitmask=128UL),
	256UL to Node(coordinate=Coordinate(column='C', row=6), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=null, below=Coordinate(column='C', row=5), upperRight=Coordinate(column='D', row=7), lowerRight=Coordinate(column='D', row=6), upperLeft=null, lowerLeft=Coordinate(column='B', row=5)), bitmask=256UL),
	512UL to Node(coordinate=Coordinate(column='D', row=2), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='D', row=3), below=null, upperRight=Coordinate(column='E', row=3), lowerRight=Coordinate(column='E', row=2), upperLeft=Coordinate(column='C', row=2), lowerLeft=null), bitmask=512UL),
	1024UL to Node(coordinate=Coordinate(column='D', row=3), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='D', row=4), below=Coordinate(column='D', row=2), upperRight=Coordinate(column='E', row=4), lowerRight=Coordinate(column='E', row=3), upperLeft=Coordinate(column='C', row=3), lowerLeft=Coordinate(column='C', row=2)), bitmask=1024UL),
	2048UL to Node(coordinate=Coordinate(column='D', row=4), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='D', row=5), below=Coordinate(column='D', row=3), upperRight=Coordinate(column='E', row=5), lowerRight=Coordinate(column='E', row=4), upperLeft=Coordinate(column='C', row=4), lowerLeft=Coordinate(column='C', row=3)), bitmask=2048UL),
	4096UL to Node(coordinate=Coordinate(column='D', row=5), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='D', row=6), below=Coordinate(column='D', row=4), upperRight=Coordinate(column='E', row=6), lowerRight=Coordinate(column='E', row=5), upperLeft=Coordinate(column='C', row=5), lowerLeft=Coordinate(column='C', row=4)), bitmask=4096UL),
	8192UL to Node(coordinate=Coordinate(column='D', row=6), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='D', row=7), below=Coordinate(column='D', row=5), upperRight=Coordinate(column='E', row=7), lowerRight=Coordinate(column='E', row=6), upperLeft=Coordinate(column='C', row=6), lowerLeft=Coordinate(column='C', row=5)), bitmask=8192UL),
	16384UL to Node(coordinate=Coordinate(column='D', row=7), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=null, below=Coordinate(column='D', row=6), upperRight=Coordinate(column='E', row=8), lowerRight=Coordinate(column='E', row=7), upperLeft=null, lowerLeft=Coordinate(column='C', row=6)), bitmask=16384UL),
	32768UL to Node(coordinate=Coordinate(column='E', row=2), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='E', row=3), below=null, upperRight=Coordinate(column='F', row=2), lowerRight=null, upperLeft=Coordinate(column='D', row=2), lowerLeft=null), bitmask=32768UL),
	65536UL to Node(coordinate=Coordinate(column='E', row=3), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='E', row=4), below=Coordinate(column='E', row=2), upperRight=Coordinate(column='F', row=3), lowerRight=Coordinate(column='F', row=2), upperLeft=Coordinate(column='D', row=3), lowerLeft=Coordinate(column='D', row=2)), bitmask=65536UL),
	131072UL to Node(coordinate=Coordinate(column='E', row=4), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='E', row=5), below=Coordinate(column='E', row=3), upperRight=Coordinate(column='F', row=4), lowerRight=Coordinate(column='F', row=3), upperLeft=Coordinate(column='D', row=4), lowerLeft=Coordinate(column='D', row=3)), bitmask=131072UL),
	262144UL to Node(coordinate=Coordinate(column='E', row=5), piece=null, isDot=false, isSpot=true, isCenter=true, neighbors=NodeNeighbors(above=Coordinate(column='E', row=6), below=Coordinate(column='E', row=4), upperRight=Coordinate(column='F', row=5), lowerRight=Coordinate(column='F', row=4), upperLeft=Coordinate(column='D', row=5), lowerLeft=Coordinate(column='D', row=4)), bitmask=262144UL),
	524288UL to Node(coordinate=Coordinate(column='E', row=6), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='E', row=7), below=Coordinate(column='E', row=5), upperRight=Coordinate(column='F', row=6), lowerRight=Coordinate(column='F', row=5), upperLeft=Coordinate(column='D', row=6), lowerLeft=Coordinate(column='D', row=5)), bitmask=524288UL),
	1048576UL to Node(coordinate=Coordinate(column='E', row=7), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='E', row=8), below=Coordinate(column='E', row=6), upperRight=Coordinate(column='F', row=7), lowerRight=Coordinate(column='F', row=6), upperLeft=Coordinate(column='D', row=7), lowerLeft=Coordinate(column='D', row=6)), bitmask=1048576UL),
	2097152UL to Node(coordinate=Coordinate(column='E', row=8), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=null, below=Coordinate(column='E', row=7), upperRight=null, lowerRight=Coordinate(column='F', row=7), upperLeft=null, lowerLeft=Coordinate(column='D', row=7)), bitmask=2097152UL),
	4194304UL to Node(coordinate=Coordinate(column='F', row=2), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='F', row=3), below=null, upperRight=Coordinate(column='G', row=2), lowerRight=null, upperLeft=Coordinate(column='E', row=3), lowerLeft=Coordinate(column='E', row=2)), bitmask=4194304UL),
	8388608UL to Node(coordinate=Coordinate(column='F', row=3), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='F', row=4), below=Coordinate(column='F', row=2), upperRight=Coordinate(column='G', row=3), lowerRight=Coordinate(column='G', row=2), upperLeft=Coordinate(column='E', row=4), lowerLeft=Coordinate(column='E', row=3)), bitmask=8388608UL),
	16777216UL to Node(coordinate=Coordinate(column='F', row=4), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='F', row=5), below=Coordinate(column='F', row=3), upperRight=Coordinate(column='G', row=4), lowerRight=Coordinate(column='G', row=3), upperLeft=Coordinate(column='E', row=5), lowerLeft=Coordinate(column='E', row=4)), bitmask=16777216UL),
	33554432UL to Node(coordinate=Coordinate(column='F', row=5), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='F', row=6), below=Coordinate(column='F', row=4), upperRight=Coordinate(column='G', row=5), lowerRight=Coordinate(column='G', row=4), upperLeft=Coordinate(column='E', row=6), lowerLeft=Coordinate(column='E', row=5)), bitmask=33554432UL),
	67108864UL to Node(coordinate=Coordinate(column='F', row=6), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='F', row=7), below=Coordinate(column='F', row=5), upperRight=Coordinate(column='G', row=6), lowerRight=Coordinate(column='G', row=5), upperLeft=Coordinate(column='E', row=7), lowerLeft=Coordinate(column='E', row=6)), bitmask=67108864UL),
	134217728UL to Node(coordinate=Coordinate(column='F', row=7), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=null, below=Coordinate(column='F', row=6), upperRight=null, lowerRight=Coordinate(column='G', row=6), upperLeft=Coordinate(column='E', row=8), lowerLeft=Coordinate(column='E', row=7)), bitmask=134217728UL),
	268435456UL to Node(coordinate=Coordinate(column='G', row=2), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='G', row=3), below=null, upperRight=Coordinate(column='H', row=2), lowerRight=null, upperLeft=Coordinate(column='F', row=3), lowerLeft=Coordinate(column='F', row=2)), bitmask=268435456UL),
	536870912UL to Node(coordinate=Coordinate(column='G', row=3), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='G', row=4), below=Coordinate(column='G', row=2), upperRight=Coordinate(column='H', row=3), lowerRight=Coordinate(column='H', row=2), upperLeft=Coordinate(column='F', row=4), lowerLeft=Coordinate(column='F', row=3)), bitmask=536870912UL),
	1073741824UL to Node(coordinate=Coordinate(column='G', row=4), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='G', row=5), below=Coordinate(column='G', row=3), upperRight=Coordinate(column='H', row=4), lowerRight=Coordinate(column='H', row=3), upperLeft=Coordinate(column='F', row=5), lowerLeft=Coordinate(column='F', row=4)), bitmask=1073741824UL),
	2147483648UL to Node(coordinate=Coordinate(column='G', row=5), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='G', row=6), below=Coordinate(column='G', row=4), upperRight=Coordinate(column='H', row=5), lowerRight=Coordinate(column='H', row=4), upperLeft=Coordinate(column='F', row=6), lowerLeft=Coordinate(column='F', row=5)), bitmask=2147483648UL),
	4294967296UL to Node(coordinate=Coordinate(column='G', row=6), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=null, below=Coordinate(column='G', row=5), upperRight=null, lowerRight=Coordinate(column='H', row=5), upperLeft=Coordinate(column='F', row=7), lowerLeft=Coordinate(column='F', row=6)), bitmask=4294967296UL),
	8589934592UL to Node(coordinate=Coordinate(column='H', row=2), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='H', row=3), below=null, upperRight=Coordinate(column='I', row=2), lowerRight=null, upperLeft=Coordinate(column='G', row=3), lowerLeft=Coordinate(column='G', row=2)), bitmask=8589934592UL),
	17179869184UL to Node(coordinate=Coordinate(column='H', row=3), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='H', row=4), below=Coordinate(column='H', row=2), upperRight=Coordinate(column='I', row=3), lowerRight=Coordinate(column='I', row=2), upperLeft=Coordinate(column='G', row=4), lowerLeft=Coordinate(column='G', row=3)), bitmask=17179869184UL),
	34359738368UL to Node(coordinate=Coordinate(column='H', row=4), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='H', row=5), below=Coordinate(column='H', row=3), upperRight=Coordinate(column='I', row=4), lowerRight=Coordinate(column='I', row=3), upperLeft=Coordinate(column='G', row=5), lowerLeft=Coordinate(column='G', row=4)), bitmask=34359738368UL),
	68719476736UL to Node(coordinate=Coordinate(column='H', row=5), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=null, below=Coordinate(column='H', row=4), upperRight=null, lowerRight=Coordinate(column='I', row=4), upperLeft=Coordinate(column='G', row=6), lowerLeft=Coordinate(column='G', row=5)), bitmask=68719476736UL),
	137438953472UL to Node(coordinate=Coordinate(column='I', row=2), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='I', row=3), below=null, upperRight=null, lowerRight=null, upperLeft=Coordinate(column='H', row=3), lowerLeft=Coordinate(column='H', row=2)), bitmask=137438953472UL),
	274877906944UL to Node(coordinate=Coordinate(column='I', row=3), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=Coordinate(column='I', row=4), below=Coordinate(column='I', row=2), upperRight=null, lowerRight=null, upperLeft=Coordinate(column='H', row=4), lowerLeft=Coordinate(column='H', row=3)), bitmask=274877906944UL),
	549755813888UL to Node(coordinate=Coordinate(column='I', row=4), piece=null, isDot=false, isSpot=true, isCenter=false, neighbors=NodeNeighbors(above=null, below=Coordinate(column='I', row=3), upperRight=null, lowerRight=null, upperLeft=Coordinate(column='H', row=5), lowerLeft=Coordinate(column='H', row=4)), bitmask=549755813888UL)
)

val bitmaskToCubeCoordinate = mapOf<ULong, CubeCoordinate>(
	1UL to CubeCoordinate.fromCoordinates(gridX=2, gridZ=5),
	2UL to CubeCoordinate.fromCoordinates(gridX=2, gridZ=4),
	4UL to CubeCoordinate.fromCoordinates(gridX=2, gridZ=3),
	8UL to CubeCoordinate.fromCoordinates(gridX=2, gridZ=2),
	16UL to CubeCoordinate.fromCoordinates(gridX=3, gridZ=5),
	32UL to CubeCoordinate.fromCoordinates(gridX=3, gridZ=4),
	64UL to CubeCoordinate.fromCoordinates(gridX=3, gridZ=3),
	128UL to CubeCoordinate.fromCoordinates(gridX=3, gridZ=2),
	256UL to CubeCoordinate.fromCoordinates(gridX=3, gridZ=1),
	512UL to CubeCoordinate.fromCoordinates(gridX=4, gridZ=5),
	1024UL to CubeCoordinate.fromCoordinates(gridX=4, gridZ=4),
	2048UL to CubeCoordinate.fromCoordinates(gridX=4, gridZ=3),
	4096UL to CubeCoordinate.fromCoordinates(gridX=4, gridZ=2),
	8192UL to CubeCoordinate.fromCoordinates(gridX=4, gridZ=1),
	16384UL to CubeCoordinate.fromCoordinates(gridX=4, gridZ=0),
	32768UL to CubeCoordinate.fromCoordinates(gridX=5, gridZ=5),
	65536UL to CubeCoordinate.fromCoordinates(gridX=5, gridZ=4),
	131072UL to CubeCoordinate.fromCoordinates(gridX=5, gridZ=3),
	262144UL to CubeCoordinate.fromCoordinates(gridX=5, gridZ=2),
	524288UL to CubeCoordinate.fromCoordinates(gridX=5, gridZ=1),
	1048576UL to CubeCoordinate.fromCoordinates(gridX=5, gridZ=0),
	2097152UL to CubeCoordinate.fromCoordinates(gridX=5, gridZ=-1),
	4194304UL to CubeCoordinate.fromCoordinates(gridX=6, gridZ=4),
	8388608UL to CubeCoordinate.fromCoordinates(gridX=6, gridZ=3),
	16777216UL to CubeCoordinate.fromCoordinates(gridX=6, gridZ=2),
	33554432UL to CubeCoordinate.fromCoordinates(gridX=6, gridZ=1),
	67108864UL to CubeCoordinate.fromCoordinates(gridX=6, gridZ=0),
	134217728UL to CubeCoordinate.fromCoordinates(gridX=6, gridZ=-1),
	268435456UL to CubeCoordinate.fromCoordinates(gridX=7, gridZ=3),
	536870912UL to CubeCoordinate.fromCoordinates(gridX=7, gridZ=2),
	1073741824UL to CubeCoordinate.fromCoordinates(gridX=7, gridZ=1),
	2147483648UL to CubeCoordinate.fromCoordinates(gridX=7, gridZ=0),
	4294967296UL to CubeCoordinate.fromCoordinates(gridX=7, gridZ=-1),
	8589934592UL to CubeCoordinate.fromCoordinates(gridX=8, gridZ=2),
	17179869184UL to CubeCoordinate.fromCoordinates(gridX=8, gridZ=1),
	34359738368UL to CubeCoordinate.fromCoordinates(gridX=8, gridZ=0),
	68719476736UL to CubeCoordinate.fromCoordinates(gridX=8, gridZ=-1),
	137438953472UL to CubeCoordinate.fromCoordinates(gridX=9, gridZ=-1),
	274877906944UL to CubeCoordinate.fromCoordinates(gridX=9, gridZ=0),
	549755813888UL to CubeCoordinate.fromCoordinates(gridX=9, gridZ=1),
)