package org.example.engine

import io.jhdf.HdfFile
import io.jhdf.api.WritableGroup
import java.nio.file.Path
import kotlin.io.path.Path
import kotlin.time.Clock.System.now
import org.jetbrains.kotlinx.multik.api.*
import org.jetbrains.kotlinx.multik.api.io.writeNPZ
import org.jetbrains.kotlinx.multik.ndarray.data.*
import org.jetbrains.kotlinx.multik.ndarray.operations.plus
import java.io.File

data class ExperienceCollector(
    // list of episodes<game states per episode<features & nodes>>
    val states: MutableList<List<D2Array<Int>>> = mutableListOf(),
    val actions: MutableList<List<D1Array<Int>>> = mutableListOf(),
    val globalStates: MutableList<List<D1Array<Float>>> = mutableListOf(),
    val rewards: MutableList<List<Int>> = mutableListOf(),
    val currentEpisodeStates: MutableList<D2Array<Int>> = mutableListOf(),
    val currentEpisodeActions: MutableList<D1Array<Int>> = mutableListOf(),
    val currentEpisodeGlobalStates: MutableList<D1Array<Float>> = mutableListOf(),
) {
  fun beginEpisode() {}

  operator fun plus(other: ExperienceCollector): ExperienceCollector {
    return ExperienceCollector(
        states = (this.states + other.states).toMutableList(),
        actions = (this.actions + other.actions).toMutableList(),
        globalStates = (this.globalStates + other.globalStates).toMutableList(),
        rewards = (this.rewards + other.rewards).toMutableList(),
    )
  }

  fun endEpisode(reward: Int) {
    states.add(currentEpisodeStates.toList())
    actions.add(currentEpisodeActions.toList())
    globalStates.add(currentEpisodeGlobalStates.toList())
    rewards.add(List<Int>(currentEpisodeStates.size) { reward })

    currentEpisodeStates.clear()
    currentEpisodeActions.clear()
    currentEpisodeGlobalStates.clear()
  }

  // action is the possibleBitMove.targetBit.toBitList() or retrievedCapturedPiecesBit
  // sum.toBitList()
  fun recordDecision(state: D2Array<Int>, action: D1Array<Int>, globalState: D1Array<Float>) {
    currentEpisodeStates.add(state)
    currentEpisodeActions.add(action)
    currentEpisodeGlobalStates.add(globalState)
  }

  fun save(agent: String, games: String) {
    mk.writeNPZ(
        Path("experience_${agent}_${games}_${now().toString().replace(":", "-")}.npz"),
        states.toPaddedD4Array(),
        actions.toPaddedD3Array(),
        rewards.toPaddedD2Array(),
    )
  }

  fun saveCurrentEpisodes(agent: String, games: String) {
    mk.writeNPZ(
        Path("experience_${agent}_${games}_${now().toString().replace(":", "-")}.npz"),
        padStates(currentEpisodeStates, currentEpisodeStates.size),
        padActions(currentEpisodeActions, currentEpisodeActions.size),
        padGlobalStates(currentEpisodeGlobalStates, currentEpisodeGlobalStates.size),
    )
  }

  fun toBuffer(): ExperienceBuffer {
    return ExperienceBuffer(
        states.toPaddedD4Array(),
        actions.toPaddedD3Array(),
        globalStates.toPaddedFloatD3Array(),
        rewards.toPaddedD2Array(),
    )
  }
}

// generated by Claude
data class ExperienceBuffer(
    val states: D4Array<Int>,
    val actions: D3Array<Int>,
    val globalStates: D3Array<Float>,
    val rewards: D2Array<Int>,
) {
  /** Serializes this [ExperienceBuffer] to an HDF5 file at [path]. */
  fun serialize(path: Path) {
    File("training_data").mkdirs()
    val file = File("training_data", path.toString())
    if (!file.exists()) {
      file.createNewFile()
    }

    HdfFile.write(file.toPath()).use { hdfFile ->
      val experience: WritableGroup = hdfFile.putGroup("experience")

      experience.putDataset("states", states.toNested4D())
      experience.putDataset("actions", actions.toNested3D())
      experience.putDataset("globalStates", globalStates.toNested3DFloat())
      experience.putDataset("rewards", rewards.toNested2D())
    }
  }

  operator fun plus(other: ExperienceBuffer): ExperienceBuffer {
    return ExperienceBuffer(
        states = this.states + other.states,
        actions = this.actions + other.actions,
        globalStates = this.globalStates + other.globalStates,
        rewards = this.rewards + other.rewards,
    )
  }

  fun load(path: Path): ExperienceBuffer {
    HdfFile(path).use { hdfFile ->
      val statesDs = hdfFile.getDatasetByPath("/experience/states")
      val actionsDs = hdfFile.getDatasetByPath("/experience/actions")
      val globalStatesDs = hdfFile.getDatasetByPath("/experience/globalStates")
      val rewardsDs = hdfFile.getDatasetByPath("/experience/rewards")

      @Suppress("UNCHECKED_CAST")
      val states = (statesDs.data as Array<Array<Array<IntArray>>>).toD4Array()
      @Suppress("UNCHECKED_CAST")
      val actions = (actionsDs.data as Array<Array<IntArray>>).toD3Array()
      @Suppress("UNCHECKED_CAST")
      val globalStates = (globalStatesDs.data as Array<Array<FloatArray>>).toD3ArrayFloat()
      @Suppress("UNCHECKED_CAST") val rewards = (rewardsDs.data as Array<IntArray>).toD2Array()

      return ExperienceBuffer(states, actions, globalStates, rewards)
    }
  }

  // --- multik -> native nested array (for writing) ---

  private fun D4Array<Int>.toNested4D(): Array<Array<Array<IntArray>>> {
    val (d0, d1, d2, d3) = shape
    return Array(d0) { i ->
      Array(d1) { j -> Array(d2) { k -> IntArray(d3) { l -> this[i, j, k, l] } } }
    }
  }

  private fun D3Array<Int>.toNested3D(): Array<Array<IntArray>> {
    val (d0, d1, d2) = shape
    return Array(d0) { i -> Array(d1) { j -> IntArray(d2) { k -> this[i, j, k] } } }
  }

  private fun D3Array<Float>.toNested3DFloat(): Array<Array<FloatArray>> {
    val (d0, d1, d2) = shape
    return Array(d0) { i -> Array(d1) { j -> FloatArray(d2) { k -> this[i, j, k] } } }
  }

  private fun D2Array<Int>.toNested2D(): Array<IntArray> {
    val (d0, d1) = shape
    return Array(d0) { i -> IntArray(d1) { j -> this[i, j] } }
  }

  // --- native nested array -> multik (for reading) ---

  private fun Array<Array<Array<IntArray>>>.toD4Array(): D4Array<Int> {
    val d0 = size
    val d1 = this[0].size
    val d2 = this[0][0].size
    val d3 = this[0][0][0].size
    val flat = IntArray(d0 * d1 * d2 * d3)
    var idx = 0
    for (i in 0 until d0) for (j in 0 until d1) for (k in 0 until d2) for (l in 0 until d3) {
      flat[idx++] = this[i][j][k][l]
    }
    return mk.ndarray(flat, d0, d1, d2, d3)
  }

  private fun Array<Array<IntArray>>.toD3Array(): D3Array<Int> {
    val d0 = size
    val d1 = this[0].size
    val d2 = this[0][0].size
    val flat = IntArray(d0 * d1 * d2)
    var idx = 0
    for (i in 0 until d0) for (j in 0 until d1) for (k in 0 until d2) {
      flat[idx++] = this[i][j][k]
    }
    return mk.ndarray(flat, d0, d1, d2)
  }

  private fun Array<Array<FloatArray>>.toD3ArrayFloat(): D3Array<Float> {
    val d0 = size
    val d1 = this[0].size
    val d2 = this[0][0].size
    val flat = FloatArray(d0 * d1 * d2)
    var idx = 0
    for (i in 0 until d0) for (j in 0 until d1) for (k in 0 until d2) {
      flat[idx++] = this[i][j][k]
    }
    return mk.ndarray(flat, d0, d1, d2)
  }

  private fun Array<IntArray>.toD2Array(): D2Array<Int> {
    val d0 = size
    val d1 = this[0].size
    val flat = IntArray(d0 * d1)
    var idx = 0
    for (i in 0 until d0) for (j in 0 until d1) {
      flat[idx++] = this[i][j]
    }
    return mk.ndarray(flat, d0, d1)
  }
}

// generated by Gemini
fun List<List<D2Array<Int>>>.toD4Array(): D4Array<Int> {
  val d1 = this.size
  val d2 = this.maxOf { it.size }
  val d3 = this[0][0].shape[0]
  val d4 = this[0][0].shape[1]

  return mk.d4arrayIndices(d1, d2, d3, d4) { i, j, k, l ->
    this[i][j][k, l]
  }
}

fun List<List<D2Array<Int>>>.toPaddedD4Array(paddingValue: Int = 0): D4Array<Int> {
  val d1 = this.size
  val maxD2 = this.maxOf { it.size } // Find max variable length
  val d3 = this[0][0].shape[0]
  val d4 = this[0][0].shape[1]

  val padded = mk.zeros<Int>(d1, maxD2, d3, d4)

  for (i in this.indices) {
    for (j in this[i].indices) {
      val matrix = this[i][j]
      for (k in 0 until d3) {
        for (l in 0 until d4) {
          padded[i, j, k, l] = matrix[k, l]
        }
      }
    }
  }
  return padded
}

fun List<List<D1Array<Int>>>.toPaddedD3Array(paddingValue: Int = 0): D3Array<Int> {
  val d1 = this.size
  val maxD2 = this.maxOf { it.size } // Find max variable length
  val d3 = this[0][0].shape[0]

  val padded = mk.zeros<Int>(d1, maxD2, d3)

  for (i in this.indices) {
    for (j in this[i].indices) {
      val matrix = this[i][j]
      for (k in 0 until d3) {
        padded[i, j, k] = matrix[k]
      }
    }
  }
  return padded
}

fun List<List<D1Array<Float>>>.toPaddedFloatD3Array(paddingValue: Int = 0): D3Array<Float> {
  val d1 = this.size
  val maxD2 = this.maxOf { it.size } // Find max variable length
  val d3 = this[0][0].shape[0]

  val padded = mk.zeros<Float>(d1, maxD2, d3)

  for (i in this.indices) {
    for (j in this[i].indices) {
      val matrix = this[i][j]
      for (k in 0 until d3) {
        padded[i, j, k] = matrix[k]
      }
    }
  }
  return padded
}

fun List<List<Int>>.toPaddedD2Array(paddingValue: Int = 0): D2Array<Int> {
  val d1 = this.size
  val d2 = this.maxOfOrNull { it.size } ?: 0

  return mk.d2arrayIndices(d1, d2) { i, j ->
    this[i].getOrElse(j) { paddingValue }
  }
}

fun padStates(
    states: List<D2Array<Int>>,
    targetLength: Int,
    padValue: Int = 0,
): D3Array<Int> {
  require(states.isNotEmpty()) { "states must not be empty to infer row/col dims" }
  require(targetLength >= states.size) {
    "targetLength ($targetLength) must be >= states.size (${states.size})"
  }

  val rows = states.first().shape[0]
  val cols = states.first().shape[1]
  val flat = IntArray(targetLength * rows * cols) { padValue }

  var idx = 0
  for (t in 0 until targetLength) {
    if (t < states.size) {
      val frame = states[t]
      require(frame.shape[0] == rows && frame.shape[1] == cols) {
        "All states must share the same shape; expected [$rows,$cols] but got " +
            "[${frame.shape[0]},${frame.shape[1]}] at index $t"
      }
      for (r in 0 until rows) {
        for (c in 0 until cols) {
          flat[idx++] = frame[r, c]
        }
      }
    } else {
      idx += rows * cols // already padValue, just advance
    }
  }

  return mk.ndarray(flat, targetLength, rows, cols)
}

/**
 * Pads a single episode's list of 1D actions into a fixed-length D2Array of shape
 * [targetLength, actionDim]. Extra timesteps beyond the list's length are filled with padValue.
 */
fun padActions(
    actions: List<D1Array<Int>>,
    targetLength: Int,
    padValue: Int = 0,
): D2Array<Int> {
  require(actions.isNotEmpty()) { "actions must not be empty to infer action dim" }
  require(targetLength >= actions.size) {
    "targetLength ($targetLength) must be >= actions.size (${actions.size})"
  }

  val actionDim = actions.first().shape[0]
  val flat = IntArray(targetLength * actionDim) { padValue }

  var idx = 0
  for (t in 0 until targetLength) {
    if (t < actions.size) {
      val action = actions[t]
      require(action.shape[0] == actionDim) {
        "All actions must share the same dim; expected $actionDim but got " +
            "${action.shape[0]} at index $t"
      }
      for (a in 0 until actionDim) {
        flat[idx++] = action[a]
      }
    } else {
      idx += actionDim
    }
  }

  return mk.ndarray(flat, targetLength, actionDim)
}

fun padGlobalStates(
    globalStates: List<D1Array<Float>>,
    targetLength: Int,
    padValue: Float = 0.0f,
): D2Array<Float> {
  require(globalStates.isNotEmpty()) { "actions must not be empty to infer action dim" }
  require(targetLength >= globalStates.size) {
    "targetLength ($targetLength) must be >= actions.size (${globalStates.size})"
  }

  val actionDim = globalStates.first().shape[0]
  val flat = FloatArray(targetLength * actionDim) { padValue }

  var idx = 0
  for (t in 0 until targetLength) {
    if (t < globalStates.size) {
      val action = globalStates[t]
      require(action.shape[0] == actionDim) {
        "All actions must share the same dim; expected $actionDim but got " +
            "${action.shape[0]} at index $t"
      }
      for (a in 0 until actionDim) {
        flat[idx++] = action[a]
      }
    } else {
      idx += actionDim
    }
  }

  return mk.ndarray(flat, targetLength, actionDim)
}
