package org.example.engine

import ncsa.hdf.`object`.Dataset
import kotlin.io.path.Path
import kotlin.time.Clock.System.now
import ncsa.hdf.`object`.Datatype
import ncsa.hdf.`object`.Group
import ncsa.hdf.`object`.h5.H5Datatype
import ncsa.hdf.`object`.h5.H5File
import org.example.engine.toPaddedD3Array
import org.jetbrains.kotlinx.multik.api.d2arrayIndices
import org.jetbrains.kotlinx.multik.api.d4arrayIndices
import org.jetbrains.kotlinx.multik.api.io.writeNPZ
import org.jetbrains.kotlinx.multik.api.mk
import org.jetbrains.kotlinx.multik.api.ndarray
import org.jetbrains.kotlinx.multik.api.zeros
import org.jetbrains.kotlinx.multik.ndarray.data.D1Array
import org.jetbrains.kotlinx.multik.ndarray.data.D2Array
import org.jetbrains.kotlinx.multik.ndarray.data.D3Array
import org.jetbrains.kotlinx.multik.ndarray.data.D4Array
import org.jetbrains.kotlinx.multik.ndarray.data.get
import org.jetbrains.kotlinx.multik.ndarray.data.set
import org.jetbrains.kotlinx.multik.ndarray.operations.plus
import org.jetbrains.kotlinx.multik.ndarray.operations.plusAssign


data class ExperienceCollector(
    // list of episodes<game states per episode<features & nodes>>
    val states: MutableList<List<D2Array<Int>>> = mutableListOf(),
    val actions: MutableList<List<D1Array<Int>>> = mutableListOf(),
    val rewards: MutableList<List<Int>> = mutableListOf(),
    val currentEpisodeStates: MutableList<D2Array<Int>> = mutableListOf(),
    val currentEpisodeActions: MutableList<D1Array<Int>> = mutableListOf(),
) {
  fun beginEpisode() {}

  fun endEpisode(reward: Int) {
    states.add(currentEpisodeStates)
//    actions.add(currentEpisodeActions)
    rewards.add(List<Int>(currentEpisodeStates.size) { reward })

    currentEpisodeStates.clear()
    currentEpisodeActions.clear()
  }

  // action is the possibleBitMove.targetBit.toBitList() or retrievedCapturedPiecesBit
  // sum.toBitList()
  fun recordDecision(state: D2Array<Int>, action: D1Array<Int>) {
    currentEpisodeStates.add(state)
    currentEpisodeActions.add(action)
  }

  fun save(agent: String, games: String) {
    mk.writeNPZ(
        Path("experience_${agent}_${games}_${now().toString().replace(":", "-")}.npz"),
        states.toPaddedD4Array(),
        actions.toPaddedD3Array(),
        rewards.toPaddedD2Array(),
    )
  }

  fun saveCurrentEpisodes(agent: String, games: String) {
    mk.writeNPZ(
      Path("experience_${agent}_${games}_${now().toString().replace(":", "-")}.npz"),
      padStates(currentEpisodeStates, currentEpisodeStates.size),
      padActions(currentEpisodeActions, currentEpisodeActions.size),
    )
  }

  fun toBuffer(): ExperienceBuffer {
    return ExperienceBuffer(
        states.toPaddedD4Array(),
        actions.toPaddedD3Array(),
        rewards.toPaddedD2Array(),
    )
  }
}

// generated by Claude
data class ExperienceBuffer(
    val states: D4Array<Int>,
    val actions: D3Array<Int>,
    val rewards: D2Array<Int>,
) {
  fun serialize(h5File: H5File) {
    h5File.open()
    try {
      val experience: Group = h5File.createGroup("experience", null)
      val intType = H5Datatype(Datatype.CLASS_INTEGER, 4, Datatype.ORDER_LE, Datatype.SIGN_2)

      val statesDims = states.shape.map { it.toLong() }.toLongArray()
      h5File.createScalarDS(
          "states",
          experience,
          intType,
          statesDims,
          null,
          statesDims,
          0,
          states.toFlatArray4D(),
      )

      val actionsDims = actions.shape.map { it.toLong() }.toLongArray()
      h5File.createScalarDS(
          "actions",
          experience,
          intType,
          actionsDims,
          null,
          actionsDims,
          0,
          actions.toFlatArray3D(),
      )

      val rewardsDims = rewards.shape.map { it.toLong() }.toLongArray()
      h5File.createScalarDS(
          "rewards",
          experience,
          intType,
          rewardsDims,
          null,
          rewardsDims,
          0,
          rewards.toFlatArray2D(),
      )
    } finally {
      h5File.close()
    }
  }

  operator fun plus(other: ExperienceBuffer): ExperienceBuffer {
    return ExperienceBuffer(
      states = this.states + other.states,
      actions = this.actions + other.actions,
      rewards = this.rewards + other.rewards,
    )
  }

  fun loadExperience(h5File: H5File): ExperienceBuffer {
    h5File.open()
    try {
      val statesDs = h5File.get("/experience/states") as Dataset
      val actionsDs = h5File.get("/experience/actions") as Dataset
      val rewardsDs = h5File.get("/experience/rewards") as Dataset

      val states = statesDs.read4D()
      val actions = actionsDs.read3D()
      val rewards = rewardsDs.read2D()

      return ExperienceBuffer(states = states, actions = actions, rewards = rewards)
    } finally {
      h5File.close()
    }
  }

  private fun D4Array<Int>.toFlatArray4D(): IntArray {
    val (d0, d1, d2, d3) = shape
    val out = IntArray(d0 * d1 * d2 * d3)
    var idx = 0
    for (i in 0 until d0) for (j in 0 until d1) for (k in 0 until d2) for (l in 0 until d3) {
      out[idx++] = this[i, j, k, l]
    }
    return out
  }

  private fun D3Array<Int>.toFlatArray3D(): IntArray {
    val (d0, d1, d2) = shape
    val out = IntArray(d0 * d1 * d2)
    var idx = 0
    for (i in 0 until d0) for (j in 0 until d1) for (k in 0 until d2) {
      out[idx++] = this[i, j, k]
    }
    return out
  }


  private fun D2Array<Int>.toFlatArray2D(): IntArray {
    val (d0, d1) = shape
    val out = IntArray(d0 * d1)
    var idx = 0
    for (i in 0 until d0) for (j in 0 until d1) {
      out[idx++] = this[i, j]
    }
    return out
  }

  private fun Dataset.read4D(): D4Array<Int> {
    val dims = dims
    require(dims.size == 4) { "Expected 4D dataset, got ${dims.size}D" }
    val flat = read() as IntArray
    return mk.ndarray(flat, dims[0].toInt(), dims[1].toInt(), dims[2].toInt(), dims[3].toInt())
  }

  private fun Dataset.read3D(): D3Array<Int> {
    val dims = dims
    require(dims.size == 3) { "Expected 4D dataset, got ${dims.size}D" }
    val flat = read() as IntArray
    return mk.ndarray(flat, dims[0].toInt(), dims[1].toInt(), dims[2].toInt())
  }

  private fun Dataset.read2D(): D2Array<Int> {
    val dims = dims
    require(dims.size == 2) { "Expected 2D dataset, got ${dims.size}D" }
    val flat = read() as IntArray
    return mk.ndarray(flat, dims[0].toInt(), dims[1].toInt())
  }
}

// generated by Gemini
fun List<List<D2Array<Int>>>.toD4Array(): D4Array<Int> {
  val d1 = this.size
  val d2 = this.maxOf { it.size }
  val d3 = this[0][0].shape[0]
  val d4 = this[0][0].shape[1]

  return mk.d4arrayIndices(d1, d2, d3, d4) { i, j, k, l ->
    this[i][j][k, l]
  }
}

fun List<List<D2Array<Int>>>.toPaddedD4Array(paddingValue: Int = 0): D4Array<Int> {
  val d1 = this.size
  val maxD2 = this.maxOf { it.size } // Find max variable length
  val d3 = this[0][0].shape[0]
  val d4 = this[0][0].shape[1]

  val padded = mk.zeros<Int>(d1, maxD2, d3, d4)

  for (i in this.indices) {
    for (j in this[i].indices) {
      val matrix = this[i][j]
      for (k in 0 until d3) {
        for (l in 0 until d4) {
          padded[i, j, k, l] = matrix[k, l]
        }
      }
    }
  }
  return padded
}

fun List<List<D1Array<Int>>>.toPaddedD3Array(paddingValue: Int = 0): D3Array<Int> {
  val d1 = this.size
  val maxD2 = this.maxOf { it.size } // Find max variable length
  val d3 = this[0][0].shape[0]

  val padded = mk.zeros<Int>(d1, maxD2, d3)

  for (i in this.indices) {
    for (j in this[i].indices) {
      val matrix = this[i][j]
      for (k in 0 until d3) {
          padded[i, j, k] = matrix[k]
      }
    }
  }
  return padded
}

fun List<List<Int>>.toPaddedD2Array(paddingValue: Int = 0): D2Array<Int> {
  val d1 = this.size
  val d2 = this.maxOfOrNull { it.size } ?: 0

  return mk.d2arrayIndices(d1, d2) { i, j ->
    this[i].getOrElse(j) { paddingValue }
  }
}

fun padStates(
  states: List<D2Array<Int>>,
  targetLength: Int,
  padValue: Int = 0,
): D3Array<Int> {
  require(states.isNotEmpty()) { "states must not be empty to infer row/col dims" }
  require(targetLength >= states.size) {
    "targetLength ($targetLength) must be >= states.size (${states.size})"
  }

  val rows = states.first().shape[0]
  val cols = states.first().shape[1]
  val flat = IntArray(targetLength * rows * cols) { padValue }

  var idx = 0
  for (t in 0 until targetLength) {
    if (t < states.size) {
      val frame = states[t]
      require(frame.shape[0] == rows && frame.shape[1] == cols) {
        "All states must share the same shape; expected [$rows,$cols] but got " +
            "[${frame.shape[0]},${frame.shape[1]}] at index $t"
      }
      for (r in 0 until rows) {
        for (c in 0 until cols) {
          flat[idx++] = frame[r, c]
        }
      }
    } else {
      idx += rows * cols // already padValue, just advance
    }
  }

  return mk.ndarray(flat, targetLength, rows, cols)
}

/**
 * Pads a single episode's list of 1D actions into a fixed-length D2Array
 * of shape [targetLength, actionDim]. Extra timesteps beyond the list's
 * length are filled with padValue.
 */
fun padActions(
  actions: List<D1Array<Int>>,
  targetLength: Int,
  padValue: Int = 0,
): D2Array<Int> {
  require(actions.isNotEmpty()) { "actions must not be empty to infer action dim" }
  require(targetLength >= actions.size) {
    "targetLength ($targetLength) must be >= actions.size (${actions.size})"
  }

  val actionDim = actions.first().shape[0]
  val flat = IntArray(targetLength * actionDim) { padValue }

  var idx = 0
  for (t in 0 until targetLength) {
    if (t < actions.size) {
      val action = actions[t]
      require(action.shape[0] == actionDim) {
        "All actions must share the same dim; expected $actionDim but got " +
            "${action.shape[0]} at index $t"
      }
      for (a in 0 until actionDim) {
        flat[idx++] = action[a]
      }
    } else {
      idx += actionDim
    }
  }

  return mk.ndarray(flat, targetLength, actionDim)
}